### ISSUE TITLE
Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?

### ISSUE THREAD

**Issue by codewithmashi** [metaloozee/summarizeai#8]
Showing this Error Here's the Full one

Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
    at neon (/vercel/path0/.next/server/chunks/752.js:11:5653)
    at 30167 (/vercel/path0/.next/server/chunks/475.js:1:10229)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at 84518 (/vercel/path0/.next/server/chunks/523.js:11:140)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at 41087 (/vercel/path0/.next/server/app/(home)/page.js:1:1411)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at t (/vercel/path0/.next/server/app/(home)/page.js:1:2725)
    at /vercel/path0/.next/server/app/(home)/page.js:1:2771
    at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1275)
> Build error occurred
Error: Failed to collect page data for /
    at /vercel/path0/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

**Comment by metaloozee** [comment]
create a `.env.local` file inside the root directory and add simply add the api keys.

**Comment by codewithmashi** [comment]
Can you tell in which format?
for example ;- GOOGLE=1289fhdhfhajehj*********

??

**Comment by metaloozee** [comment]
you can refer the `env.mjs` file found in the root directory to see what all variables are required.

acquire the required variables and simply add those in the `.env.local` file by following this format.
```
GOOGLE_API_KEY="<your_key_goes_here>"
DATABASE_URL="<your_key_goes_here>"
```

**Comment by codewithmashi** [comment]
still showing same error

GOOGLE_API_KEY="AIzaSyC*********nVtHDE************************"

this is wht i add there

**Comment by metaloozee** [comment]
add every required environment variable, according to the error you provided it seems like you haven't provided the database connection string.

if you've already added then let me know

**Comment by codewithmashi** [comment]
⨯ NeonDbError: relation "summaries" does not exist
    at execute (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\node_modules_@neondatabase_serverless_index_mjs_d735c7._.js:4959:46)
    at async NeonHttpPreparedQuery.execute (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\node_modules_drizzle-orm_f28b3a._.js:5770:24)
    at async SummariesIndexPage (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\_aa6799._.js:760:18)
digest: "3559672983"
 ⨯ NeonDbError: relation "summaries" does not exist
    at execute (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\node_modules_@neondatabase_serverless_index_mjs_d735c7._.js:4959:46)
    at async NeonHttpPreparedQuery.execute (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\node_modules_drizzle-orm_f28b3a._.js:5770:24)
    at async SummariesIndexPage (D:\AI Short Maker\quickvid\.next\server\chunks\ssr\_aa6799._.js:760:18)
digest: "3559672983"
 GET / 500 in 8887ms
 
 showing this error now after adding Databaseurl

**Comment by metaloozee** [comment]
run the following commands:

to create the migration file:
```
pnpm run db:generate
```

to apply the database schema or any changes:
```
pnpm run db:push
```

if this is your first time, you might encounter an error related to vectors. 
to resolve it, enable the `pgvector` extension in your database by running this query:
```
CREATE EXTENSION vector;
```

**Comment by codewithmashi** [comment]
PS DA:\AITool\quickvid> pnpm run db:push

> quickvid@2.0.0 db:push DA:\AITool\quickvid
> drizzle-kit push

drizzle-kit: v0.22.8
drizzle-orm: v0.31.4

No config path provided, using default path
Reading config file 'DA:\AITool\quickvid\drizzle.config.ts'
 Error  Either connection "url" or "host", "database" are required for database connection
 ELIFECYCLE  Command failed with exit code 1.
 
 showing this after running second command

**Comment by metaloozee** [comment]
kindly re-check your database url.
